<table width="470" border="0" cellspacing="0" cellpadding="3" class="text11">
        <tr> 
          
    <td><img src="../_images/new_point.gif" width="12" height="11" align="absmiddle"> 
      <a href="../printpage.php" target="_blank">Druckfreundliche Version</a><img src="../_images/trans.gif" width="40" height="8"><img src="../_images/new_point.gif" width="12" height="11" align="absmiddle"> 
      <a href="../home/empfehlen.php" target="_self">Weiterempfehlen</a><img src="../_images/trans.gif" width="40" height="8"><img src="../_images/new_point.gif" width="12" height="11" align="absmiddle"> 
      <a href="javascript:;" onClick="window.external.AddFavorite('http://typisch-buch.pluspunkt.de', 'Typisch-buch.pluspunkt.de');">Bookmark</a></td>
        </tr>
        <tr> 
          
    <td><img src="../_images/new_point.gif" width="12" height="11" align="absmiddle"> 
      <a href="../home/impressum.php" target="_self">Impressum</a><img src="../_images/trans.gif" width="92" height="8"><font color="#999999">&copy; 
      Pluspunkt Unternehmensentwicklung GmbH 2004</font><!--Beginn Unsere Partner -->
<a href="http://<?php  echo "$_SERVER[HTTP_HOST]"?>/unsere-partner/unsere-partner.php" title="Unsere Partner"><img src="http://www.werbeagentur-munster.de/partner/trans.gif" border="0" width="1" height="1" alt="Unsere Partner"></a>
<!--Ende Unsere Partner --></td>
        </tr>
      </table>
