<table width="780" border="0" cellspacing="0" cellpadding="0">
    <tr bgcolor="#E6E6E6" valign="top"> 
      <td width="181" background="../_images/new_header_hgl.gif" height="110"><img src="../_images/newbestellung.gif" width="125" height="21"><font color="#CCCCCC">&nbsp;<a href="http://www4.bol.de/pages/functions.phtml?function=detail&IdentNr=3825651&id=dEnEmNRlzWUAABnnGcsAAAAZ&lk=&ProvID=0&md=5" target="_blank"><img src="../_images/newbol.gif" width="49" height="21" border="0" alt="Das Buch (inkl. DVD) bei bol.de bestellen"></a></font><br>
        <img src="../_images/trans.gif" width="52" height="70"><img src="../_images/logo.jpg" width="124" height="46"></td>
      <td width="599" bgcolor="#E6E6E6" background="../_images/new_header_hgr.gif" height="110"> 
        <table width="591" border="0" cellspacing="0" cellpadding="0" height="40">
          <tr valign="top"> 
            <td width="457"><font color="#CCCCCC"><img src="../_images/trans.gif" width="1" height="5"><a href="http://www.amazon.de/exec/obidos/ASIN/3763930876/ref=pd_rhf_p_1/302-3717862-8027264&tag=l013-21" target="_blank"><img src="../_images/newamazon.gif" width="63" height="21" border="0" alt="Das Buch (inkl. DVD) bei amazon.de bestellen"></a>&nbsp;&nbsp;<br>
              <br>
              <font color="#999999"><br>
              <b><font color="#666666">&nbsp;&nbsp;&nbsp;Potenziale erlebter Kommunikation</font></b><br>
            &nbsp;&nbsp;&nbsp;[ Buch inklusive DVD im Buchhandel erh&auml;ltlich 
            ]</font></font></td>
            <td width="134"><img src="../_images/trans.gif" width="1" height="5"><br>
              <img src="../_images/newbook.jpg" width="116" height="103"></td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
