
<table width="114" border="0" cellspacing="0" cellpadding="3" class="menue">
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/index.php" target="_self">Home</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/vorwort.php" target="_self">Vorwort</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/buch-idee.php" target="_self">Die Buch
        Idee</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/inhalt.php" target="_self">Der Inhalt</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../autoren/index.php" target="_self">Die Autoren</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../leseproben/index.php" target="_self">Leseproben</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/herausgeber.php" target="_self">Herausgeber</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/partner.php" target="_self">Partner</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../presse/index.php" target="_self">Presse</a></div>
    </td>
  </tr>
  <tr>
    <td width="16">&nbsp;</td>
    <td width="86">
      <div align="right"><a href="../home/impressum.php" target="_self">Impressum</a></div>
    </td>
  </tr>
</table>