<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="Copyright" content="Pluspunkt Unternehmensentwicklung GmbH">
<meta name="Keywords" content="Typen, typisch, Kommunikation, Pluspunkt, Mission, Vision, Motivation, Mensch Veränderung, Sympathie, Signale, Outfit, Kleider, Arbeitswelt, Fragen, Aktion kulinarisch, kochen, Partyservice, Termine, Ideen, Energie, Synergie, Umwelt, Persönlichkeit, Team, Organisation, Umwelttechnologie, Fachkompetenz, Sozialkompetenz, Management, Pyramide, Mandant, Zahlenkolonnen">
<meta name="Description" content="Zwölf Autoren ganz unterschiedlicher Charaktere schreiben in ihrem Stil über jenen Aspekt der Kommunikation, in dem sie sich spezialisiert haben.">
<meta name="robots" content="index,follow">
<meta name="revisit-after" content="1 days">
<meta http-equiv="Pragma" content="no-cache">