<?php
/**
 * Gutenix_Pro_Dynamic_CSS_File class
 *
 * @package gutenix-pro
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

if ( ! class_exists( 'Gutenix_Pro_Dynamic_CSS_File' ) ) {

	/**
	 * Define Gutenix_Pro_Dynamic_CSS_File class
	 */
	class Gutenix_Pro_Dynamic_CSS_File {

		/**
		 * A reference to an instance of this class.
		 *
		 * @since  1.0.0
		 * @access private
		 * @var    Gutenix_Pro_Dynamic_CSS_File
		 */
		private static $instance = null;

		/**
		 * Check cache dynamic css is enabled.
		 *
		 * @since  1.0.0
		 * @access private
		 * @var    null|bool
		 */
		private $is_cache_dynamic_css = null;

		/**
		 * Dynamic CSS directory path.
		 *
		 * @since  1.0.0
		 * @access private
		 * @var    null|string
		 */
		private $dynamic_dir = null;

		/**
		 * Dynamic CSS directory url.
		 *
		 * @since  1.0.0
		 * @access private
		 * @var    null|string
		 */
		private $dynamic_url = null;

		/**
		 * Constructor for the class
		 *
		 * @since  1.0.0
		 * @access public
		 * @return void
		 */
		public function init() {
			add_filter( 'gutenix_get_customizer_options', array( $this, 'customizer_options' ) );

			add_action( 'after_setup_theme',  array( $this, 'maybe_create_css_file' ), 11 );
			add_action( 'after_setup_theme',  array( $this, 'remove_print_inline_style' ), 20 );
			add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_dynamic_css' ) );

			add_action( 'customize_save_after', array( $this, 'remove_css_file' ) );
		}

		/**
		 * Added Dynamic CSS options to customizer.
		 *
		 * @since  1.0.0
		 * @access public
		 * @param  array $options Theme customizer options.
		 * @return array
		 */
		public function customizer_options( $options = array() ) {

			$ext_options = array(
				/** `Dynamic CSS` section */
				'dynamic_css' => array(
					'title'    => esc_html__( 'Dynamic CSS', 'gutenix-pro' ),
					'priority' => 30,
					'type'     => 'section',
					'panel'    => 'general_settings',
				),
				'cache_dynamic_css' => array(
					'title'       => esc_html__( 'Cache dynamic CSS', 'gutenix-pro' ),
					'description' => esc_html__( 'Cache CSS generated by your options to boost performance.', 'gutenix-pro' ),
					'section'     => 'dynamic_css',
					'default'     => false,
					'field'       => 'checkbox',
					'type'        => 'control',
				),
			);

			$options['options'] = array_merge( $options['options'], $ext_options );

			return $options;
		}

		/**
		 * Check cache dynamic css is enabled.
		 *
		 * @since  1.0.0
		 * @access public
		 * @return bool|mixed|null
		 */
		public function is_cache_dynamic_css() {

			if ( null !== $this->is_cache_dynamic_css ) {
				return $this->is_cache_dynamic_css;
			}

			$this->is_cache_dynamic_css = gutenix_theme()->customizer->get_value( 'cache_dynamic_css' ) && ! is_customize_preview();

			return $this->is_cache_dynamic_css;
		}

		/**
		 * Maybe create Dynamic CSS file
		 *
		 * @since  1.0.0
		 * @access public
		 * @return void
		 */
		public function maybe_create_css_file() {

			if ( ! $this->is_cache_dynamic_css() ) {
				return;
			}

			if ( ! $this->ensure_dynamic_dir() ) {
				return;
			}

			if ( $this->dynamic_css_exists() ) {
				return;
			}

			$css = gutenix_theme()->dynamic_css->get_inline_css();

			file_put_contents( $this->dynamic_css_path(), htmlspecialchars_decode( $css ) );
		}

		/**
		 * Enqueue Dynamic CSS File
		 *
		 * @since  1.0.0
		 * @access public
		 * @return void
		 */
		public function enqueue_dynamic_css() {

			if ( ! $this->is_cache_dynamic_css() ) {
				return;
			}

			if ( ! $this->dynamic_css_exists() ) {
				return;
			}

			wp_enqueue_style(
				'gutenix-theme-dynamic-style',
				$this->dynamic_css_url(),
				array( 'gutenix-theme-style' ),
				filemtime( $this->dynamic_css_path() )
			);
		}

		/**
		 * Remove print inline Dynamic CSS.
		 *
		 * @since  1.0.0
		 * @access public
		 * @return void
		 */
		public function remove_print_inline_style() {

			if ( ! $this->is_cache_dynamic_css() ) {
				return;
			}

			if ( ! $this->dynamic_css_exists() ) {
				return;
			}

			remove_action( 'wp_enqueue_scripts', array( gutenix_theme()->dynamic_css, 'add_inline_css' ), 99 );
		}

		/**
		 * Remove CSS file on options save
		 *
		 * @since  1.0.0
		 * @access public
		 * @return void
		 */
		public function remove_css_file() {
			if ( $this->dynamic_css_exists() ) {
				unlink( $this->dynamic_css_path() );
			}
		}

		/**
		 * Check if Dynamic CSS file exists
		 *
		 * @since  1.0.0
		 * @access public
		 * @return bool
		 */
		public function dynamic_css_exists() {
			return file_exists( $this->dynamic_css_path() );
		}

		/**
		 * Return path to Dynamic CSS file
		 *
		 * @since  1.0.0
		 * @access public
		 * @return string
		 */
		public function dynamic_css_path() {
			return $this->dynamic_dir() . 'dynamic-style.css';
		}

		/**
		 * Return url to Dynamic CSS file
		 *
		 * @since  1.0.0
		 * @access public
		 * @return string
		 */
		public function dynamic_css_url() {
			return $this->dynamic_url() . 'dynamic-style.css';
		}

		/**
		 * Returns Dynamic CSS directory URL
		 *
		 * @since  1.0.0
		 * @access public
		 * @return string
		 */
		public function dynamic_url() {

			if ( null !== $this->dynamic_url ) {
				return $this->dynamic_url;
			}

			$upload_dir        = wp_upload_dir();
			$upload_base_dir   = $upload_dir['baseurl'];
			$this->dynamic_url = trailingslashit( $upload_base_dir ) . 'gutenix/';

			if ( is_ssl() ) {
				$this->dynamic_url = set_url_scheme( $this->dynamic_url );
			}

			return $this->dynamic_url;
		}

		/**
		 * Returns Dynamic CSS directory path
		 *
		 * @since  1.0.0
		 * @access public
		 * @return string
		 */
		public function dynamic_dir() {

			if ( null !== $this->dynamic_dir ) {
				return $this->dynamic_dir;
			}

			$upload_dir        = wp_upload_dir();
			$upload_base_dir   = $upload_dir['basedir'];
			$this->dynamic_dir = trailingslashit( $upload_base_dir ) . 'gutenix/';

			return $this->dynamic_dir;
		}

		/**
		 * Ensure that CSS directory exists and try to create if not.
		 *
		 * @since  1.0.0
		 * @access public
		 * @return bool
		 */
		public function ensure_dynamic_dir() {

			if ( file_exists( $this->dynamic_dir() ) ) {
				return true;
			} else {
				return mkdir( $this->dynamic_dir() );
			}
		}

		/**
		 * Returns the instance.
		 *
		 * @since  1.0.0
		 * @access public
		 * @return Gutenix_Pro_Dynamic_CSS_File
		 */
		public static function get_instance() {
			// If the single instance hasn't been set, set it now.
			if ( null == self::$instance ) {
				self::$instance = new self;
			}

			return self::$instance;
		}
	}

}

if ( ! function_exists( 'gutenix_pro_dynamic_css_file' ) ) {

	/**
	 * Returns instance of Gutenix_Pro_Dynamic_CSS_File
	 *
	 * @since  1.0.0
	 * @return Gutenix_Pro_Dynamic_CSS_File
	 */
	function gutenix_pro_dynamic_css_file() {
		return Gutenix_Pro_Dynamic_CSS_File::get_instance();
	}
}
